### ISSUE TITLE
how to prevent duplicate users?

### ISSUE THREAD

**Issue by aleprovencio** [centrifugal/adjacent#3]
Hello!
When using chat on 2 different tabs centrifuge creates 2 objects for the same user (maybe because different timestamps?). Is there a way to prevent that? Is this on adjacent's or javascript's side?

**Comment by FZambia** [comment]
Hello, Centrifugo does not limit amount of tabs for user. This can be not what you want for chat but in most situations we want user to receive real-time messages in all open browser tabs. But you can detect this in your javascript code based on knowledge of user IDs.

Also if Centrifugo prevent opening several browser tabs then situation possible when user opened your chat at home and left computer on then went to work and failed to open chat there. So I think you should make this logic on your application level.

**Comment by aleprovencio** [comment]
Yeah I got what you mean. However, I think on my case I would not want to prevent the connection but actually to use the existing centrifuge/centrifugo object if there's already one.

As I do not yet trust my javascript abilities, can you please give me a hint on how I can make this verification before creating the object, and connect to it afterwards?

**Comment by FZambia** [comment]
You can not use existing connection from another browser tab.

You can use call to API on your backend side to check if user already connected before providing connection credentials to template.

Also you can call presence using Javascript API right after connection to Centrifugo established and decide what to do based on information received.

But it all seems weird to me. I don't see a problem having lots of tabs with chat open simultaneously. Let user decide how many tabs he can open. All you need to do in this case - show only unique users in channel to prevent showing duplicate user nicknames.

**Comment by aleprovencio** [comment]
That's it. Thanks again @FZambia.
And cheers for your cool software!

**Comment by FZambia** [comment]
Welcome! Please note that in near future I am planning to release version of Centrifugo with only one project support - see https://github.com/centrifugal/centrifugo/issues/33 . This will require updating all libraries to new versions as some backwards incompatible changes will be introduced and some simplifications in configuration file.
