### ISSUE TITLE
Publish to user

### ISSUE THREAD

**Issue by ghost** [centrifugal/adjacent#5]
How i can publish message to any user(s) by user id?

**Comment by FZambia** [comment]
@fdhadzh hello! Actually Centrifugo does not have such terminology as publish to user. You can only publish to channel. So just let your user subscribe on channel containing its id (I suggest using `user limited channels` - see user channel boundary section at https://fzambia.gitbooks.io/centrifugal/content/server/channels.html). For example `personal#3456` where 3456 is user ID. Each user will subscribe on its own channel. And then just publish messages to this channel so user will receive them.

**Comment by ghost** [comment]
Thanks, @FZambia
